name: Step 0 # Iniciar Exercício

on:
  workflow_dispatch:
  # NOTE: Make sure the repository is a template before enabling this trigger.
  # push:
  #   branches:
  #     - main

permissions:
  contents: write
  actions: write
  issues: write

env:
  STEP_1_FILE: ".github/steps/1-step.md"

jobs:
  start_exercise:
    if: |
      !github.event.repository.is_template
    name: Iniciar Exercício
    uses: dev-pods/exercise-toolkit/.github/workflows/start-exercise.yml@v0.1.1
    with:
      exercise-title: "Integrar Figma MCP com Copilot"
      intro-message: "Vamos configurar o uso de Figma MCP com Copilot"

  post_next_step_content:
    name: Publicar conteúdo do próximo passo
    runs-on: ubuntu-latest
    needs: [start_exercise]
    env:
      ISSUE_NUMBER: ${{ needs.start_exercise.outputs.issue-number }}
      ISSUE_REPOSITORY: ${{ github.repository }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Obter templates de resposta
        uses: actions/checkout@v5
        with:
          repository: dev-pods/exercise-toolkit
          path: exercise-toolkit
          ref: v0.1.1

      - name: Criar comentário - adicionar conteúdo do passo
        uses: GrantBirki/comment@v2.1.1
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          file: ${{ env.STEP_1_FILE }}
          vars: |
            full_repo_name: ${{ github.repository }}

      - name: Criar comentário - observando progresso
        uses: GrantBirki/comment@v2.1.1
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          file: exercise-toolkit/markdown-templates/step-feedback/watching-for-progress.md

      - name: Habilitar próximo workflow
        run: |
          gh workflow enable "Step 1"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
